version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/lg-mdm-react-test/
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_package_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_app_status.sh
      timeout: 300
      runas: ubuntu
