apiVersion: apps/v1
kind: Deployment
metadata:
  name: APPNAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APPNAME
  template:
    metadata:
      labels:
        app: APPNAME
    spec:
      containers:
        - name: APPNAME
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
        
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: APPNAME
spec:
  type: LoadBalancer
  selector:
    app: APPNAME
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80