export const COUNT_BY_LOCATION_REQUEST = 'COUNT_BY_LOCATION_REQUEST';
export const COUNT_BY_LOCATION_SUCCESS = 'COUNT_BY_LOCATION_SUCCESS';
export const COUNT_BY_LOCATION_FAILURE = 'COUNT_BY_LOCATION_FAILURE';
