export const DEVICE_STATUS_EDIT_REQUEST = 'DEVICE_STATUS_EDIT_REQUEST';
export const DEVICE_STATUS_EDIT_SUCCESS = 'DEVICE_STATUS_EDIT_SUCCESS';
export const DEVICE_STATUS_EDIT_FAILURE = 'DEVICE_STATUS_EDIT_FAILURE';
