export const EMAIL_SETTINGS_EDIT_REQUEST = 'EMAIL_SETTINGS_EDIT_REQUEST';
export const EMAIL_SETTINGS_EDIT_SUCCESS = 'EMAIL_SETTINGS_EDIT_SUCECSS';
export const EMAIL_SETTINGS_EDIT_FAILURE = 'EMAIL_SETTINGS_EDIT_FAILURE';
