export const EMAILTEMPLATES_EDIT_REQUEST = 'EMAILTEMPLATES_EDIT_REQUEST';
export const EMAILTEMPLATES_EDIT_SUCCESS = 'EMAILTEMPLATES_EDIT_SUCCESS ';
export const EMAILTEMPLATES_EDIT_FAILURE = 'EMAILTEMPLATES_EDIT_FAILURE ';
