export const USERS_EDIT_REQUEST = 'USERS_EDIT_REQUEST';
export const USERS_EDIT_SUCCESS = 'USERS_EDIT_SUCCESS';
export const USERS_EDIT_FAILURE = 'USERS_EDIT_FAILURE';
export const USERS_EDIT_PAGE = 'USERS_EDIT_PAGE';
