export const USERS_NEW_REQUEST = 'USERS_NEW_REQUEST';
export const USERS_NEW_SUCCESS = 'USERS_NEW_SUCCESS ';
export const USERS_NEW_FAILURE = 'USERS_NEW_FAILURE ';
export const USERS_NEW_PAGE = 'USERS_NEW_PAGE';
